export const categories = [
  {
    title: "العروض",
    meals: [
      {
        id: 50,
        image: "/images/prost1.jpg",
        promo: "جديد",
        title: "وجبة دينر ميل",
        desc: "قطعتين بروست بالعضم / 2 عيش / بطاطس / تومية / كلوسلو",
        price: 120,
      },
      {
        id: 51,
        image: "/images/prost2.jpg",
        promo: "طبق الشيف",

        title: "وجبة سنايبر الراتب",
        desc: "3 قطع بروست بالعضم / 4 عيش / بطاطس / تومية / كلوسلو",
        price: 155,
      },
      {
        id: 61,
        image: "/images/3arabi1.jpg",
        promo: "حار",

        title: "شاورما عربي دجاج",

        desc: " سندوتش شاورما مقطع / بطاطس / تومية / كولسلو / مخلل / عيش محمر",
        price: 110,
        options: {
          sizes: [
            { label: "S", price: 110 },
            { label: "M", price: 155 },
            { label: "L", price: 170 },
          ],
        },
      },
      {
        id: 62,
        image: "/images/3arabi2.jpg",
        title: "بوكس شاورما دجاج اكسترا",
        desc: " سندوتشين ونص شاورما مقطع 15 قطعه / بطاطس / تومية / كولسلو / مخلل / عيش محمر",
        price: 200,
        promo: "عرض خاص",
      },
    ],
  },
  {
    title: "قسم الأكثر مبيعا",
    meals: [
      {
        id: 50,
        image: "/images/prost1.jpg",
        title: "وجبة دينر ميل",
        desc: "قطعتين بروست بالعضم / 2 عيش / بطاطس / تومية / كلوسلو",
        price: 120,
      },
      {
        id: 51,
        image: "/images/prost2.jpg",
        title: "وجبة سنايبر الراتب",
        desc: "3 قطع بروست بالعضم / 4 عيش / بطاطس / تومية / كلوسلو",
        price: 155,
      },
      {
        id: 61,
        image: "/images/3arabi1.jpg",
        title: "شاورما عربي دجاج",
        desc: " سندوتش شاورما مقطع / بطاطس / تومية / كولسلو / مخلل / عيش محمر",
        price: 110,
        options: {
          sizes: [
            { label: "S", price: 110 },
            { label: "M", price: 155 },
            { label: "L", price: 170 },
          ],
        },
      },
      {
        id: 62,
        image: "/images/3arabi2.jpg",
        title: "بوكس شاورما دجاج اكسترا",
        desc: " سندوتشين ونص شاورما مقطع 15 قطعه / بطاطس / تومية / كولسلو / مخلل / عيش محمر",
        price: 200,
      },
    ],
  },
  {
    title: "قسم البيتزا",
    meals: [
      {
        id: 1,
        image: "/images/pizza-suses.jpg",
        title: "بيتزا مارجريتا",
        desc: "جبنةرومي / حبنة موتزاريلا",
        price: 90,
        options: {
          sizes: [
            { label: "M", price: 90 },
            { label: "L", price: 120 },
          ],
        },
      },
      {
        id: 2,
        image: "/images/pizza-chicken.jpg",
        title: "بيتزا خضراوات",
        desc: "فلفل / زيتون / ذرة / مشروم",
        price: 95,
        options: {
          sizes: [
            { label: "M", price: 95 },
            { label: "L", price: 130 },
          ],
        },
      },
      {
        id: 3,
        image: "/images/pizza-suses.jpg",
        title: "بيتزا تشيزلافريز",
        desc: "جبنة رومي / جبنة موتزاريلا / جبنة كيري / جبنة شيدر",
        price: 110,
        options: {
          sizes: [
            { label: "M", price: 110 },
            { label: "L", price: 145 },
          ],
        },
      },
      {
        id: 4,
        image: "/images/pizza-chicken.jpg",
        title: "بيتزا مشكل فراخ",
        desc: " ذرة / مكسيكي / مكسيكان / مشروم",
        price: 140,
        options: {
          sizes: [
            { label: "M", price: 140 },
            { label: "L", price: 170 },
          ],
        },
      },
      {
        id: 5,
        image: "/images/pizza-suses.jpg",
        title: "بيتزا شيش طاووق",
        desc: " فلفل / زيتون / شيش طاووق",
        price: 130,
        options: {
          sizes: [
            { label: "M", price: 130 },
            { label: "L", price: 175 },
          ],
        },
      },
      {
        id: 6,
        image: "/images/pizza-chicken.jpg",
        title: "بيتزا شاورما فراخ",
        desc: " جبنة رومي / جبنة موتزاريلا / شاورما دجاج",
        price: 140,
        options: {
          sizes: [
            { label: "M", price: 140 },
            { label: "L", price: 170 },
          ],
        },
      },
      {
        id: 7,
        image: "/images/pizza-suses.jpg",
        title: "بيتزا تشيكن باربيكيو",
        desc: " جبنة رومي / جينة موتزاريلا / دجاج / صوص باربكيو",
        price: 120,
        options: {
          sizes: [
            { label: "M", price: 120 },
            { label: "L", price: 155 },
          ],
        },
      },
      {
        id: 8,
        image: "/images/pizza-chicken.jpg",
        title: "بيتزا تشيكن رانش",
        desc: " جبنة رومي / جينة موتزاريلا / دجاج / صوص رانش",
        price: 140,
        options: {
          sizes: [
            { label: "M", price: 140 },
            { label: "L", price: 175 },
          ],
        },
      },
      {
        id: 9,
        image: "/images/pizza-suses.jpg",
        title: "بيتزا زنجر",
        desc: " جبنة موتزاريلا / بيبروني / استربس ",
        price: 140,
        options: {
          sizes: [
            { label: "M", price: 140 },
            { label: "L", price: 170 },
          ],
        },
      },
      {
        id: 10,
        image: "/images/pizza-chicken.jpg",
        title: "بيتزا تشيكن اسبيشيال ",
        desc: "",
        price: 140,
        options: {
          sizes: [
            { label: "M", price: 140 },
            { label: "L", price: 180 },
          ],
        },
      },
      {
        id: 11,
        image: "/images/pizza-suses.jpg",
        title: "بيتزا لحم مفروم",
        desc: " جبنة موتزاريلا / فلفل / زيتون / لحم مفروم",
        price: 110,
        options: {
          sizes: [
            { label: "M", price: 110 },
            { label: "L", price: 170 },
          ],
        },
      },
      {
        id: 12,
        image: "/images/pizza-chicken.jpg",
        title: "بيتزا بيبروني",
        desc: " جبنة رومي / جبنة موتزاريلا / بيبروني",
        price: 120,
        options: {
          sizes: [
            { label: "M", price: 120 },
            { label: "L", price: 160 },
          ],
        },
      },
      {
        id: 13,
        image: "/images/pizza-suses.jpg",
        title: "بيتزا بسطرمة",
        desc: " جبنة موتزاريلا / فلفل / زيتون / بسطرمة",
        price: 140,
        options: {
          sizes: [
            { label: "M", price: 140 },
            { label: "L", price: 190 },
          ],
        },
      },
      {
        id: 14,
        image: "/images/pizza-chicken.jpg",
        title: "بيتزا سوبر سوبريم",
        desc: " جبنة موتزاريلا / فلفل / زيتون / بسطرمة / سوسيس / سجق",
        price: 150,
        options: {
          sizes: [
            { label: "M", price: 150 },
            { label: "L", price: 185 },
          ],
        },
      },
      {
        id: 15,
        image: "/images/pizza-chicken.jpg",
        title: "بيتزا سوسيس",
        desc: " جبنة موتزاريلا / فلفل / زيتون / سوسيس",
        price: 120,
        options: {
          sizes: [
            { label: "M", price: 120 },
            { label: "L", price: 160 },
          ],
        },
      },
      {
        id: 16,
        image: "/images/pizza-suses.jpg",
        title: "بيتزا ميكس لحوم",
        desc: "",
        price: 140,
        options: {
          sizes: [
            { label: "M", price: 140 },
            { label: "L", price: 180 },
          ],
        },
      },
      {
        id: 17,
        image: "/images/pizza-chicken.jpg",
        title: "بيتزا جمبري",
        desc: " جبنة موتزاريلا / فلفل / زيتون / جمبري",
        price: 210,
        options: {
          sizes: [
            { label: "M", price: 210 },
            { label: "L", price: 290 },
          ],
        },
      },
      {
        id: 18,
        image: "/images/pizza-suses.jpg",
        title: "بيتزا سي فود",
        desc: "  جبنة موتزاريلا / فلفل / زيتون / جمبري / كاليماري / كابوريا",
        price: 200,
        options: {
          sizes: [
            { label: "M", price: 200 },
            { label: "L", price: 280 },
          ],
        },
      },
    ],
  },
  {
    title: "قسم شاورما الحمة",
    meals: [
      {
        id: 19,
        image: "/images/4awrma1.jpg",
        title: "سندوتش شاورما لحم كيزر",
        desc: "",
        price: 50,
      },
      {
        id: 20,
        image: "/images/4awrma1.jpg",
        title: "سندوتش شاورما لحم ",
        desc: "",
        price: 60,
        options: {
          sizes: [
            { label: "M", price: 60 },
            { label: "L", price: 80 },
          ],
        },
      },
      {
        id: 21,
        image: "/images/4awrma1.jpg",
        title: " سندوتش شاورما لحم صاروخ",
        desc: "",
        price: 110,
      },
      {
        id: 22,
        image: "/images/4awrma1.jpg",
        title: "شومة شاورما لحم",
        desc: "",
        price: 150,
      },
      {
        id: 23,
        image: "/images/4awrma1.jpg",
        title: "فتة شاورما لحم ",
        desc: "",
        price: 115,
        options: {
          sizes: [
            { label: "M", price: 115 },
            { label: "L", price: 150 },
          ],
        },
      },
      {
        id: 24,
        image: "/images/4awrma1.jpg",
        title: "ربع كيلو شاورما لحم",
        desc: "",
        price: 235,
      },
      {
        id: 25,
        image: "/images/4awrma1.jpg",
        title: "نص كيلو شاورما لحم",
        desc: "",
        price: 480,
      },
    ],
  },
  {
    title: "قسم شاورما الدجاج",
    meals: [
      {
        id: 26,
        image: "/images/4awrma1.jpg",
        title: "سندوتش شاورما دجاج كيزر",
        desc: "تومية + مخلل",
        price: 45,
      },
      {
        id: 27,
        image: "/images/4awrma1.jpg",
        title: "سندوتش شاورما دجاج ",
        desc: "",
        price: 55,
        options: {
          sizes: [
            { label: "M", price: 55 },
            { label: "L", price: 65 },
          ],
        },
      },
      {
        id: 28,
        image: "/images/4awrma1.jpg",
        title: " سندوتش شاورما دجاج صاروخ",
        desc: "",
        price: 80,
      },
      {
        id: 29,
        image: "/images/4awrma1.jpg",
        title: "شومة شاورما دجاج",
        desc: "",
        price: 130,
      },
      {
        id: 30,
        image: "/images/4awrma1.jpg",
        title: "فتة شاورما دجاج ",
        desc: "شاورما / ارز / تومية ع الرز / عيش محمص / بطاطس / تومية / مخلل",
        price: 95,
        options: {
          sizes: [
            { label: "M", price: 95 },
            { label: "L", price: 120 },
          ],
        },
      },
      {
        id: 31,
        image: "/images/4awrma1.jpg",
        title: "ربع كيلو شاورما دجاج",
        desc: "شاورما / عيش سوري / بطاطس / تومية / مخلل",
        price: 200,
      },
      {
        id: 32,
        image: "/images/4awrma1.jpg",
        title: "نص كيلو شاورما دجاج",
        desc: "شاورما / عيش سوري / بطاطس / تومية / مخلل",
        price: 310,
      },
    ],
  },
  {
    title: "قسم دجاج الشواية",
    meals: [
      {
        id: 33,
        image: "/images/chicken-fahm.jpg",
        title: "ربع دجاجة ورك شواية",
        desc: "ورك / ارز / تومية / بطاطس / مخلل / 2 عيش",
        price: 110,
      },
      {
        id: 34,
        image: "/images/chicken-fahm.jpg",
        title: "ربع دجاجة صدر شواية",
        desc: "صدر / ارز / تومية / بطاطس / مخلل / 2 عيش",
        price: 130,
      },
      {
        id: 35,
        image: "/images/chicken-fahm.jpg",
        title: "نص دجاجة شواية",
        desc: "نص دجاجة / ارز / 2 تومية / 2 بطاطس / 2 مخلل / 4 عيش",
        price: 195,
      },
      {
        id: 36,
        image: "/images/chicken-fahm.jpg",
        title: "دجاجة شواية",
        desc: " دجاجة / ارز / 2 تومية / 2 بطاطس / 2 مخلل / 4 عيش",
        price: 360,
      },
      {
        id: 37,
        image: "/images/chicken-fahm.jpg",
        title: "دجاجة شواية توفير",
        desc: "",
        price: 320,
      },
    ],
  },
  {
    title: "قسم ع الفحم",
    meals: [
      {
        id: 38,
        image: "/images/chicken-fahm.jpg",
        title: "ربع دجاجة ع الفحم",
        desc: "ربع دجاجة / ارز / طحينة / مخلل / بطاطس",
        price: 110,
        options: {
          sizes: [
            { label: "ورك", price: 110 },
            { label: "صدر", price: 130 },
          ],
        },
      },
      {
        id: 39,
        image: "/images/chicken-fahm.jpg",
        title: "نصف دجاجة ع الفحم",
        desc: "نصف دجاجة / ارز / 2 طحينة / 2 مخلل / بطاطس كبير",
        price: 200,
      },
      {
        id: 40,
        image: "/images/chicken-fahm.jpg",
        title: "دجاجة ع الفحم",
        desc: " دجاجة / ارز / 3 طحينة / 2 مخلل / بطاطس كبير",
        price: 380,
      },
      {
        id: 41,
        image: "/images/chicken-fahm.jpg",
        title: "وجبة السنجل",
        desc: "ورك / 2 كفتة لحمة / ارز / طحينة / مخلل / بطاطس ",
        price: 170,
      },
      {
        id: 42,
        image: "/images/chicken-fahm.jpg",
        title: "وجبة شيش طاووق",
        desc: "ارز / 6 شيش ورك / بطاطس / طحينة / مخلل / 2 عيش",
        price: 180,
      },
      {
        id: 43,
        image: "/images/chicken-fahm.jpg",
        title: "وجبة كفتة لحم",
        desc: "ارز / 5 كفتة لحمة / طحينة / مخلل / بطاطس / 2 عيش",
        price: 210,
      },
      {
        id: 44,
        image: "/images/chicken-fahm.jpg",
        title: "وجبة كفتة دجاج",
        desc: "ارز / كفتة دجاج / طحينة / مخلل / بطاطس / 2 عيش",
        price: 165,
      },
      {
        id: 45,
        image: "/images/chicken-fahm.jpg",
        title: "وجبة ميكس جريل",
        desc: "ارز / 2 كفتة دجاج / 2 كفتة لحمة / 2 شيش / صدر / طحينة / مخلل / بطاطس / 2 عيش",
        price: 230,
      },
      {
        id: 46,
        image: "/images/chicken-fahm.jpg",
        title: "وجبة التوينز",
        desc: "ارز / نصف دجاجة / 2 كفتة لحمة / 4 كفتة دجاج / 2 طحينة / 2 مخلل / بطاطس كبير",
        price: 315,
      },
      {
        id: 47,
        image: "/images/chicken-fahm.jpg",
        title: "صينية الراتب",
        desc: "ربع دجاجة / 3 كفتة لحمة / 3 كفتة دجاج / 3 شيش / 1 ك ارز / 3 طحينة / 3 مخلل / 3 بطاطس / 9 عيش",
        price: 1600,
      },
      {
        id: 48,
        image: "/images/chicken-fahm.jpg",
        title: "ميكس دجاج",
        desc: " صدر / 2 كفتة لحمة / 3 شيش ",
        price: 160,
      },
      {
        id: 49,
        image: "/images/chicken-fahm.jpg",
        title: "وجبة جريلد تشيكن",
        desc: "ارز / 3 صدور فحم / طحينه / بطاطس / مخلل / عيش",
        price: 170,
      },
    ],
  },
  {
    title: "قسم البروست",
    meals: [
      {
        id: 50,
        image: "/images/prost1.jpg",
        title: "وجبة دينر ميل",
        desc: "قطعتين بروست بالعضم / 2 عيش / بطاطس / تومية / كلوسلو",
        price: 120,
      },
      {
        id: 51,
        image: "/images/prost2.jpg",
        title: "وجبة سنايبر الراتب",
        desc: "3 قطع بروست بالعضم / 4 عيش / بطاطس / تومية / كلوسلو",
        price: 155,
      },
      {
        id: 52,
        image: "/images/prost1.jpg",
        title: "وجبة سنايبر الراتب",
        desc: "3   قطع استربس / 4 عيش / بطاطس / تومية / كلوسلو",
        price: 125,
      },
      {
        id: 53,
        image: "/images/prost2.jpg",
        title: "وجبة 8 قطع بالعضم",
        desc: "8 قطع بروست / 6 عيش / بطاطس كبير / 2 تومية / 2 كولسلو / 2 صوص شيدر",
        price: 390,
      },
      {
        id: 54,
        image: "/images/prost1.jpg",
        title: "وجبة ميكس بروست واستربس",
        desc: "5 قطع بروست / 5 قطع استربس / 8 عيش / 2 بطاطس كبير / 2 تومية / 2 كلوسلو / 2 صوص شيدر",
        price: 420,
      },
      {
        id: 55,
        image: "/images/prost2.jpg",
        title: "سندوتش تشيكن كلاسيك",
        desc: "صدر فيليه / 30 جم مايونيز / خس / خيار مخلل / شريحة جبنة شيدر / صوص باربيكيو",
        price: 110,
      },
      {
        id: 56,
        image: "/images/prost1.jpg",
        title: "سندوتش سوبر كلاسيك",
        desc: "صدر فيليه / 30 جم مايونيز / خس / خيار مخلل / شريحة جبنة شيدر / رومي مدخن / صوص باربيكيو",
        price: 120,
      },
      {
        id: 57,
        image: "/images/prost2.jpg",
        title: "سندوتش زنجر",
        desc: "صدر فيليه حار / 30 جم مايونيز / خس / خيار مخلل / شريحة جبنة شيدر / صوص تكساس حار",
        price: 110,
      },
      {
        id: 58,
        image: "/images/prost1.jpg",
        title: "سندوتش تشيكن بيكون",
        desc: "صدر فيليه / 30 جم مايونيز / خس / خيار مخلل / 30 جم بيف بيكون / 30 جم صوص باربيكيو",
        price: 130,
      },
      {
        id: 59,
        image: "/images/prost2.jpg",
        title: "وجبة استربس اطفال",
        desc: " 2 قطعه استربس / 2 عيش / عصير اطفال / بطاطس",
        price: 100,
      },
      {
        id: 60,
        image: "/images/prost1.jpg",
        title: "وجبة دبوس اطفال",
        desc: " 2 قطعه دبوس بالعضم / 2 عيش / عصير اطفال / بطاطس",
        price: 100,
      },
    ],
  },
  {
    title: "قسم العربي",
    meals: [
      {
        id: 61,
        image: "/images/3arabi1.jpg",
        title: "شاورما عربي دجاج",
        desc: " سندوتش شاورما مقطع / بطاطس / تومية / كولسلو / مخلل / عيش محمر",
        price: 110,
        options: {
          sizes: [
            { label: "S", price: 110 },
            { label: "M", price: 155 },
            { label: "L", price: 170 },
          ],
        },
      },
      {
        id: 62,
        image: "/images/3arabi2.jpg",
        title: "بوكس شاورما دجاج اكسترا",
        desc: " سندوتشين ونص شاورما مقطع 15 قطعه / بطاطس / تومية / كولسلو / مخلل / عيش محمر",
        price: 200,
      },
      {
        id: 63,
        image: "/images/3arabi3.jpg",
        title: "شاورما عربي لحم",
        desc: " سندوتش شاورما مقطع / بطاطس / تومية / كولسلو / مخلل / عيش محمر",
        price: 120,
        options: {
          sizes: [
            { label: "S", price: 120 },
            { label: "M", price: 170 },
            { label: "L", price: 190 },
          ],
        },
      },
      {
        id: 64,
        image: "/images/3arabi1.jpg",
        title: "بوكس شاورما دجاج اكسترا",
        desc: " سندوتشين ونص شاورما مقطع 15 قطعه / بطاطس / تومية / كولسلو / مخلل / عيش محمر",
        price: 220,
      },
      {
        id: 65,
        image: "/images/3arabi2.jpg",
        title: "بوكس ميكس اكسترا",
        desc: "",
        price: 210,
      },
      {
        id: 66,
        image: "/images/3arabi3.jpg",
        title: "كرسبي عربي ",
        desc: " سندوتش كرسبي مقطع / بطاطس / تومية / كولسلو / مخلل / عيش محمر",
        price: 110,
        options: {
          sizes: [
            { label: "M", price: 110 },
            { label: "L", price: 175 },
          ],
        },
      },
      {
        id: 67,
        image: "/images/3arabi1.jpg",
        title: "شيش عربي ",
        desc: " سندوتش شيش مقطع / بطاطس / تومية / كولسلو / مخلل / عيش محمر",
        price: 120,
        options: {
          sizes: [
            { label: "M", price: 120 },
            { label: "L", price: 190 },
          ],
        },
      },
    ],
  },
  {
    title: "قسم السندوتشات",
    meals: [
      {
        id: 68,
        image: "/images/4awrma1.jpg",
        title: "سندوتش كباب ( سوري - فرنساوي )",
        desc: "",
        price: 140,
      },
      {
        id: 69,
        image: "/images/4awrma1.jpg",
        title: "سندوتش كفتة لحم ( سوري - فرنساوي )",
        desc: "",
        price: 95,
      },
      {
        id: 70,
        image: "/images/4awrma1.jpg",
        title: "سندوتش كفتة دجاج ( سوري - فرنساوي )",
        desc: "",
        price: 75,
      },
      {
        id: 71,
        image: "/images/4awrma1.jpg",
        title: "سندوتش شيش طاووق ( سوري - فرنساوي )",
        desc: "",
        price: 90,
      },
      {
        id: 72,
        image: "/images/4awrma1.jpg",
        title: "سندوتش صدور مشوية ( سوري - فرنساوي )",
        desc: "",
        price: 95,
      },
      {
        id: 73,
        image: "/images/4awrma1.jpg",
        title: "سندوتش بطاطس",
        desc: "",
        price: 45,
      },
      {
        id: 74,
        image: "/images/4awrma1.jpg",
        title: "سندوتش بطاطس موتزاريلا",
        desc: "",
        price: 55,
      },
      {
        id: 75,
        image: "/images/4awrma1.jpg",
        title: "سوبر كرانشي",
        desc: "",
        price: 95,
      },
      {
        id: 76,
        image: "/images/4awrma1.jpg",
        title: " كرسبي",
        desc: "",
        price: 90,
      },
      {
        id: 77,
        image: "/images/4awrma1.jpg",
        title: " تشكن رانش",
        desc: "",
        price: 120,
      },
    ],
  },
  {
    title: "قسم البرجر",
    meals: [
      {
        id: 78,
        image: "/images/wagba1.JPG",
        title: "كلاسيك برجر",
        desc: "قطعة برجر / مايونيز / خس / خيار مخلل / صوص الف جزيره / طماطم",
        price: 100,
      },
      {
        id: 79,
        image: "/images/wagba2.JPG",
        title: "تشيز برجر",
        desc: "قطعة برجر / مايونيز / خس / خيار مخلل / صوص الف جزيره / اميركان تشيز / طماطم",
        price: 120,
      },
      {
        id: 80,
        image: "/images/wagba1.JPG",
        title: "مشروم برجر",
        desc: "",
        price: 130,
      },
    ],
  },
  {
    title: "قسم الوجبات",
    meals: [
      {
        id: 81,
        image: "/images/wagba1.JPG",
        title: "وجبة اسكالوب بانية",
        desc: "ارز / 3 قطع اسكالوب / بطاطس / تومية / مخلل",
        price: 180,
      },
      {
        id: 82,
        image: "/images/wagba2.JPG",
        title: "وجبة تشيكن فاهيتا",
        desc: "",
        price: 150,
      },
      {
        id: 83,
        image: "/images/wagba1.JPG",
        title: "وجبة تشيكن اسكالوب",
        desc: "",
        price: 170,
      },
      {
        id: 84,
        image: "/images/wagba2.JPG",
        title: "وجبة شيش طاووق غربي",
        desc: "",
        price: 190,
      },
    ],
  },
  {
    title: "قسم المكرونات",
    meals: [
      {
        id: 85,
        image: "/images/pasta1.jpg",
        title: "نجرسكو دجاج",
        desc: "",
        price: 130,
      },
      {
        id: 86,
        image: "/images/pasta2.jpg",
        title: "نجرسكو دجاج شيدر",
        desc: "",
        price: 145,
      },
      {
        id: 87,
        image: "/images/pasta3.jpg",
        title: "تشكن الفريدو",
        desc: "",
        price: 140,
      },
      {
        id: 88,
        image: "/images/pasta4.jpg",
        title: "اسباجتي بلونيز",
        desc: "",
        price: 110,
      },
      {
        id: 89,
        image: "/images/pasta1.jpg",
        title: "بشاميل لحم مفروم",
        desc: "",
        price: 120,
      },
    ],
  },
  {
    title: "قسم الشوربة",
    meals: [
      {
        id: 90,
        image: "/images/burger2.png",
        title: "كريمة بالدجاج",
        desc: "",
        price: 80,
      },
      {
        id: 91,
        image: "/images/burger2.png",
        title: "كريمة مشروم",
        desc: "",
        price: 70,
      },
    ],
  },
  {
    title: "قسم الريزو",
    meals: [
      {
        id: 92,
        image: "/images/wagba1.JPG",
        title: "ريزو شاورما",
        desc: "ارز بسمتي / شاورما / صوص باربيكيو",
        price: 90,
      },
      {
        id: 93,
        image: "/images/wagba2.JPG",
        title: "ريزو فاهيتا",
        desc: "ارز بسمتي / فاهيتا / صوص باربيكيو",
        price: 80,
      },
      {
        id: 94,
        image: "/images/wagba1.JPG",
        title: "ريزو كرسبي",
        desc: "ارز بسمتي / قطع استربس / صوص باربيكيو",
        price: 85,
      },
      {
        id: 95,
        image: "/images/wagba2.JPG",
        title: "ريزو مكسيكي حار",
        desc: "ارز / استربس حار / صوص باربيكيو",
        price: 110,
      },
    ],
  },
  {
    title: "قسم الماريا",
    meals: [
      {
        id: 96,
        image: "/images/maria1.jpg",
        title: "ماريا شاورما",
        desc: "شاورما / عيش ماريا / موتزاريلا / توميه / بطاطس / مخلل / شيدر / 2 محمره",
        price: 145,
      },
      {
        id: 97,
        image: "/images/maria2.jpg",
        title: "ماريا شاورما سوري",
        desc: "شاورما / عيش سوري / موتزاريلا / توميه / بطاطس / مخلل / شيدر",
        price: 170,
      },
      {
        id: 98,
        image: "/images/maria1.jpg",
        title: "ماريا كرسبي",
        desc: "كرسبي / موتزاريلا / توميه / بطاطس / مخلل / شيدر",
        price: 130,
      },
    ],
  },
  {
    title: "قسم المناقيش",
    meals: [
      {
        id: 99,
        image: "/images/mana2e41.jpg",
        title: "لبنة زعتر",
        desc: "",
        price: 35,
      },
      {
        id: 100,
        image: "/images/mana2e42.jpg",
        title: "لبنة مع شرائح ليمون",
        desc: "",
        price: 35,
      },
      {
        id: 101,
        image: "/images/mana2e41.jpg",
        title: "مشكل جبن",
        desc: "",
        price: 35,
      },
      {
        id: 102,
        image: "/images/mana2e42.jpg",
        title: "سنفوره",
        desc: "",
        price: 35,
      },
      {
        id: 103,
        image: "/images/mana2e41.jpg",
        title: "حلوم سادة",
        desc: "",
        price: 45,
      },
      {
        id: 104,
        image: "/images/mana2e42.jpg",
        title: "حلوم محمرة",
        desc: "",
        price: 50,
      },
      {
        id: 105,
        image: "/images/mana2e41.jpg",
        title: "حلوم زعتر",
        desc: "",
        price: 50,
      },
      {
        id: 106,
        image: "/images/mana2e42.jpg",
        title: "حلوم زيتون",
        desc: "",
        price: 50,
      },
      {
        id: 107,
        image: "/images/mana2e41.jpg",
        title: "هوت دوج موتزاريلا",
        desc: "",
        price: 45,
      },
      {
        id: 108,
        image: "/images/mana2e42.jpg",
        title: "حلوم سوسيس",
        desc: "",
        price: 50,
      },
      {
        id: 109,
        image: "/images/mana2e41.jpg",
        title: "بيبروني",
        desc: "",
        price: 45,
      },
      {
        id: 110,
        image: "/images/mana2e42.jpg",
        title: "لحم صفيحه",
        desc: "",
        price: 50,
      },
      {
        id: 111,
        image: "/images/mana2e41.jpg",
        title: "سجق موتزاريلا",
        desc: "",
        price: 70,
      },
      {
        id: 112,
        image: "/images/mana2e42.jpg",
        title: "رومي مدخن مفتوح",
        desc: "",
        price: 45,
      },
      {
        id: 113,
        image: "/images/mana2e41.jpg",
        title: "سوبر كرانشي",
        desc: "",
        price: 80,
      },
      {
        id: 114,
        image: "/images/mana2e42.jpg",
        title: "ميكسيكان موتزاريلا",
        desc: "",
        price: 65,
      },
      {
        id: 115,
        image: "/images/mana2e41.jpg",
        title: "شيش طاووق",
        desc: "",
        price: 60,
      },
      {
        id: 116,
        image: "/images/mana2e42.jpg",
        title: "منقوشة الراتب",
        desc: "",
        price: 65,
      },
    ],
  },
  {
    title: "قسم البرك",
    meals: [
      {
        id: 117,
        image: "/images/perak1.jpg",
        title: "سوارية",
        desc: "فلفل / زيتون / طماطم / موتزاريلا",
        price: 25,
      },
      {
        id: 118,
        image: "/images/perak2.jpg",
        title: "سبانخ",
        desc: "",
        price: 30,
      },
      {
        id: 119,
        image: "/images/perak3.jpg",
        title: "كيري",
        desc: "",
        price: 35,
      },
      {
        id: 120,
        image: "/images/perak1.jpg",
        title: "موتزاريلا",
        desc: "",
        price: 35,
      },
      {
        id: 121,
        image: "/images/perak2.jpg",
        title: "شيكولاته",
        desc: "",
        price: 35,
      },
      {
        id: 122,
        image: "/images/perak3.jpg",
        title: "شيكولاته موز",
        desc: "",
        price: 55,
      },
    ],
  },
  {
    title: "قسم السلطات والمقبلات",
    meals: [
      {
        id: 123,
        image: "/images/maria1.jpg",
        title: "تومية",
        desc: "",
        price: 15,
      },
      {
        id: 124,
        image: "/images/maria1.jpg",
        title: "كول سلو",
        desc: "",
        price: 15,
      },
      {
        id: 124,
        image: "/images/maria1.jpg",
        title: "طحينة",
        desc: "",
        price: 20,
      },
      {
        id: 125,
        image: "/images/maria1.jpg",
        title: "خضراء",
        desc: "",
        price: 30,
      },
      {
        id: 126,
        image: "/images/maria1.jpg",
        title: "تبوله",
        desc: "",
        price: 55,
      },
      {
        id: 127,
        image: "/images/maria1.jpg",
        title: "فتوش",
        desc: "",
        price: 60,
      },
      {
        id: 128,
        image: "/images/maria1.jpg",
        title: "سيزر سلاد",
        desc: "",
        price: 50,
      },
      {
        id: 129,
        image: "/images/maria1.jpg",
        title: "تشيكن سيزر سلاد",
        desc: "",
        price: 85,
      },
      {
        id: 130,
        image: "/images/maria1.jpg",
        title: "ارز بسمتي",
        desc: "",
        price: 25,
        options: {
          sizes: [
            { label: "M", price: 25 },
            { label: "L", price: 35 },
          ],
        },
      },
      {
        id: 131,
        image: "/images/maria1.jpg",
        title: "حلقات بصل",
        desc: "",
        price: 35,
      },

      {
        id: 132,
        image: "/images/maria1.jpg",
        title: "أصابع موتزاريلا",
        desc: "",
        price: 55,
      },
      {
        id: 133,
        image: "/images/maria1.jpg",
        title: "بطاطس",
        desc: "",
        price: 30,
        options: {
          sizes: [
            { label: "M", price: 30 },
            { label: "L", price: 35 },
          ],
        },
      },
      {
        id: 134,
        image: "/images/maria1.jpg",
        title: "بطاطس شيدر",
        desc: "",
        price: 50,
      },
      {
        id: 135,
        image: "/images/maria1.jpg",
        title: "تكساس فرايز",
        desc: "",
        price: 95,
      },
      {
        id: 136,
        image: "/images/maria1.jpg",
        title: "كرسبي تشكن فرايز",
        desc: "",
        price: 120,
      },
    ],
  },
  {
    title: "قسم الإضافات",
    meals: [
      {
        id: 137,
        image: "/images/maria1.jpg",
        title: "حشو اطراف",
        desc: "",
        price: 20,
      },
      {
        id: 138,
        image: "/images/maria1.jpg",
        title: "إضافة موتزاريلا",
        desc: "",
        price: 25,
      },
      {
        id: 139,
        image: "/images/maria1.jpg",
        title: "صوص رانش",
        desc: "",
        price: 10,
      },
      {
        id: 140,
        image: "/images/maria1.jpg",
        title: "صوص شيدر",
        desc: "",
        price: 10,
      },
      {
        id: 141,
        image: "/images/maria1.jpg",
        title: "إضافه رومي مدخن",
        desc: "",
        price: 15,
      },
      {
        id: 142,
        image: "/images/maria1.jpg",
        title: "إضافه دبس رومان",
        desc: "",
        price: 10,
      },
    ],
  },
];
